### ISSUE TITLE
Make python test failures show which condition caused failure

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.topology#1152]
I have built my first python test case, so it's possible I'm just missing something. 

I add multiple conditions, but when my test fails, I can't actually tell which condition failed: 

```
AssertionError: Test failed for topology: singleChannel
```
The traceback also doesn't show anything helpful: 

```
Failure
Traceback (most recent call last):
  File "/home/streamsadmin/anaconda3/lib/python3.5/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/home/streamsadmin/anaconda3/lib/python3.5/unittest/case.py", line 600, in run
    testMethod()
  File "/home/streamsadmin/PycharmProjects/TestSingleChannelTranscriptsBuilder/transcriptTests.py", line 86, in test_transcript
    self.tester.test(self.test_ctxtype, self.test_config)
  File "/home/streamsadmin/anaconda3/lib/python3.5/site-packages/streamsx/topology/tester.py", line 426, in test
    assert passed, "Test failed for topology: " + self.topology.name
```

It would be helpful to see which condition actually caused the failure.

**Comment by ddebrunner** [comment]
@Alex-Cook4 Were you running standalone, distributed or against streaming analytics service?

**Comment by ddebrunner** [comment]
We now report the condition that failed.
