### ISSUE TITLE
Running unittests that uses topology.Tester fail using nose

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1266]
Using the `Tester` in a `unittest.Testcase` with `nose` results in an error like:

```
======================================================================
ERROR: Failure: TypeError (__init__() missing 1 required positional argument: 'topology')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/streamsadmin/anaconda3/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/streamsadmin/anaconda3/lib/python3.5/site-packages/nose/loader.py", line 523, in makeTest
    return self._makeTest(obj, parent)
  File "/home/streamsadmin/anaconda3/lib/python3.5/site-packages/nose/loader.py", line 582, in _makeTest
    return MethodTestCase(obj)
  File "/home/streamsadmin/anaconda3/lib/python3.5/site-packages/nose/case.py", line 346, in __init__
    self.inst = self.cls()
TypeError: __init__() missing 1 required positional argument: 'topology'

```

**Comment by ddebrunner** [comment]
Looks like the `Tester.test` method is being seen as a test.

From http://nose.readthedocs.io/en/latest/finding_tests.html

looks like we can make `Tester.__test__ = False` to avoid it and its methods being seen as tests.
