### ISSUE TITLE
400:Bad Request -- when a remote build fails with WAMS beta 

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#1473]
```
SEVERE: Streaming Analytics service (debrunne-streams-wams1): The submitted archive tk5308465280918512762.zip failed to build with status failed.
Exception in thread "main" java.lang.IllegalStateException: Unexpected HTTP resource from service:400:Bad Request -- {"trace":"950b0c8c1e874196a7039ecd27877ff0","errors":[{"code":"bad_request","message":"CDISB4004E The `requestPath` field is either not specified or not valid.  Check the service API documentation."}]}
at com.ibm.streamsx.rest.StreamsRestUtils.gsonFromResponse(StreamsRestUtils.java:413)
at com.ibm.streamsx.rest.StreamsRestUtils.getGsonResponse(StreamsRestUtils.java:120)
at com.ibm.streamsx.rest.StreamingAnalyticsServiceV2.getBuildOutput(StreamingAnalyticsServiceV2.java:144)
at com.ibm.streamsx.rest.AbstractStreamingAnalyticsService.buildAndSubmitJob(AbstractStreamingAnalyticsService.java:209)
at com.ibm.streamsx.topology.internal.context.remote.RemoteBuildAndSubmitRemoteContext._submit(RemoteBuildAndSubmitRemoteContext.java:58)
at com.ibm.streamsx.topology.internal.context.remote.RemoteContextImpl.submit(RemoteContextImpl.java:12)
at com.ibm.streamsx.topology.context.remote.RemoteContextSubmit.main(RemoteContextSubmit.java:33)
<streamsx.topology.context.SubmissionResult object at 0x7fd4d5aafb00>
```

**Comment by wmarshall484** [comment]
Fixed by #1474
