### ISSUE TITLE
StreamsConnectionSample failure

### ISSUE THREAD

**Issue by apyasic** [IBMStreams/streamsx.topology#1540]
When trying to run [StreamsConnectionSample](https://github.com/IBMStreams/streamsx.topology/blob/6d760c596c40cbe71150bbf30a79a7e4ea0be1c0/samples/java/functional/src/rest/StreamsConnectionSample.java) with arguments
streamsadmin password https://localhost:8443/streams/rest/resources StreamsDomain
on Streams 4.2.4.0 I've got the following exception:
```
com.ibm.streamsx.rest.RESTException: Invalid Streams connection
Instance: 
	at com.ibm.streamsx.rest.StreamsConnection$InvalidStreamsConnection.getInstance(StreamsConnection.java:211)
	at com.ibm.streamsx.rest.StreamsConnection.getInstance(StreamsConnection.java:149)
	at TestRestAPI.main(TestRestAPI.java:35)
Caused by: javax.net.ssl.SSLHandshakeException: com.ibm.jsse2.util.h: PKIX path building failed: java.security.cert.CertPathBuilderException: unable to find valid certification path to requested target
	at com.ibm.jsse2.k.a(k.java:24)
	at com.ibm.jsse2.at.a(at.java:882)
	at com.ibm.jsse2.D.a(D.java:98)
	at com.ibm.jsse2.D.a(D.java:540)
	at com.ibm.jsse2.E.a(E.java:369)
	at com.ibm.jsse2.E.a(E.java:22)
	at com.ibm.jsse2.D.r(D.java:176)
	at com.ibm.jsse2.D.a(D.java:286)
	at com.ibm.jsse2.at.a(at.java:197)
	at com.ibm.jsse2.at.i(at.java:509)
	at com.ibm.jsse2.at.a(at.java:259)
	at com.ibm.jsse2.at.startHandshake(at.java:392)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:290)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:259)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:125)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:319)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.apache.http.client.fluent.Executor.execute(Executor.java:206)
	at com.ibm.streamsx.rest.StreamsRestUtils.getResponseString(StreamsRestUtils.java:188)
	at com.ibm.streamsx.rest.AbstractStreamsConnection.getResponseString(AbstractStreamsConnection.java:144)
	at com.ibm.streamsx.rest.AbstractStreamsConnection.init(AbstractStreamsConnection.java:104)
	at com.ibm.streamsx.rest.StreamsConnection.createDelegate(StreamsConnection.java:190)
	at com.ibm.streamsx.rest.StreamsConnection.createInstance(StreamsConnection.java:66)
	at TestRestAPI.main(TestRestAPI.java:24)
Caused by: com.ibm.jsse2.util.h: PKIX path building failed: java.security.cert.CertPathBuilderException: unable to find valid certification path to requested target
	at com.ibm.jsse2.util.f.a(f.java:148)
	at com.ibm.jsse2.util.f.b(f.java:82)
	at com.ibm.jsse2.util.e.a(e.java:5)
	at com.ibm.jsse2.aB.a(aB.java:7)
	at com.ibm.jsse2.aB.a(aB.java:104)
	at com.ibm.jsse2.aB.checkServerTrusted(aB.java:121)
	at com.ibm.jsse2.E.a(E.java:38)
	... 26 more
Caused by: java.security.cert.CertPathBuilderException: unable to find valid certification path to requested target
	at com.ibm.security.cert.PKIXCertPathBuilderImpl.buildCertPath(PKIXCertPathBuilderImpl.java:654)
	at com.ibm.security.cert.PKIXCertPathBuilderImpl.engineBuild(PKIXCertPathBuilderImpl.java:368)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:268)
	at com.ibm.jsse2.util.f.a(f.java:84)
	... 32 more

```
Please note, that the same code worked for Streams version 4.2.0.0.

**Comment by ddebrunner** [comment]
How did you create the certificate for the domain?

**Comment by ddebrunner** [comment]
Did you pass `true` as the last argument to enable insecure hosts?

**Comment by apyasic** [comment]
Insecure hosts enablement resolved the issue. Closing.
