### ISSUE TITLE
HashAdder does not inherit upstream outputSerializer

### ISSUE THREAD

**Issue by mrshenli** [IBMStreams/streamsx.topology#1571]
When the upstream operator uses a custom [`outputSerializer`](https://github.com/IBMStreams/streamsx.topology/blob/91018a0f7ad152263e0385a690d2454047bba1ee/java/execute/src/com/ibm/streamsx/topology/internal/functional/ops/AbstractPipe.java#L30), `HashAdder` might run into deserialization errors. 

```
Caused by: java.lang.RuntimeException: java.io.StreamCorruptedException: invalid stream header: 01008000
        at com.ibm.streamsx.topology.internal.spljava.SPLJavaObject.convertFrom(SPLJavaObject.java:50)
        at com.ibm.streamsx.topology.internal.functional.ops.HashAdder.process(HashAdder.java:54)
```

**Comment by ddebrunner** [comment]
Fixed by #1582
