### ISSUE TITLE
NPE in SPLStreams.convertStream() - problem with parameterized type handling

### ISSUE THREAD

**Issue by dlaboss** [IBMStreams/streamsx.topology#164]
I've been trying to create a generic Supplier<Iterable<T>> that performs an initial delay (for test code).
Seems like there's a problem with determining a parameterized type value?
 
List<Message> msgList = ...
TStream<Message> msgs = top.supplier(new DelayedSupplierIterable<>(msgList, initialDelay));
...
 
Trying to convert msgs to an SPL stream yields:

java.lang.NullPointerException
at com.ibm.streamsx.topology.spl.SPLStreams.convertStream(SPLStreams.java:104)
at com.ibm.streamsx.topology.messaging.mqtt.ProducerConnector.publish(ProducerConnector.java:142)
at com.ibm.streamsx.topology.messaging.mqtt.ProducerConnector.publish(ProducerConnector.java:114)
at com.ibm.streamsx.topology.test.messaging.mqtt.MqttStreamsTest.testConfigParams(MqttStreamsTest.java:288)
 
msgs.getTupleClass() is returning null:
    opName = "SPLConvert" + stream.getTupleClass().getSimpleName();  // (SPLStreams.java:104)
 

class DelayedSupplierIterable<T> implements Supplier<Iterable<T>>, Iterable<T>, Iterator<T>, Serializable {
    private static final long serialVersionUID = 1L;
    private final Iterable<T> data;
    private Iterator<T> iter;
    private int initialDelayMsec;
    DelayedSupplierIterable(Iterable<T> data, int initialDelayMsec) {
        this.data = data;
        this.initialDelayMsec = initialDelayMsec;
    }
    @Override
    public Iterable<T> get() {
        return this;
    }
    @Override
    public Iterator<T> iterator() {
        return this;
    }
    @Override
    public boolean hasNext() {
        if (iter==null)
            iter = data.iterator();
        return iter.hasNext();
    }
    @Override
    public T next() {
        if (iter==null)
            iter = data.iterator();
        if (initialDelayMsec != -1) {
            try {
                Thread.sleep(initialDelayMsec);
            } catch (InterruptedException e) {
                // done delaying
            }
            initialDelayMsec = -1;
        }
        return iter.next();
    }
    @Override
    public void remove() {
        throw new UnsupportedOperationException("remove");
    }
}

**Comment by dlaboss** [comment]
getting the same failure with code trying to use an SPL op within a parallel region:

        TStream<BeaconTuple> fb = BeaconStreams.beacon(topology, count);
        TStream<BeaconTuple> pb = fb.parallel(5);
        TStream<Integer> is = pb.transform(randomHashProducer());
        StreamSchema schema = getStreamSchema("tuple<int32 i>");
        // NPE in convertStream because is.getTupleClass() returns null...
        SPLStream splStream = SPLStreams.convertStream(is, myCvtFn(), schema);
