### ISSUE TITLE
Error creating a view on an end_parallel

### ISSUE THREAD

**Issue by queeniema** [IBMStreams/streamsx.topology#1742]
The error is being caused by `v = s.view()`. The workaround is to add an intermediate operator.

Error: 
```
(py35) [queeniema@streamshost2 parallel_hash_view]$ python parallel_hash_view_bundle.py
Traceback (most recent call last):
  File "parallel_hash_view_bundle.py", line 27, in <module>
    main()
  File "parallel_hash_view_bundle.py", line 16, in main
    v = s.view()
  File "/home/queeniema/ghe/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/topology.py", line 881, in view
    self._colocate(view_stream, 'view')
  File "/home/queeniema/ghe/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/_streams/_placement.py", line 119, in _colocate
    self._op().colocate(other_ops, why)
  File "/home/queeniema/ghe/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/topology.py", line 714, in _op
    raise TypeError()
TypeError
```

Application:
```
from streamsx.topology import context
from streamsx.topology.topology import *
import random
import time

cfg = {}
cfg['topology.keepArtifacts'] = True

def main():
    topo = Topology("parallel_hash_view", namespace="pythonApp")
    s = topo.source(numberGenerator)
    s = s.parallel(5, routing=Routing.HASH_PARTITIONED)
    s = s.map(lambda tuple : tuple + 19)
    s = s.end_parallel()
    s.print();
    v = s.view()
    context.submit(context.ContextTypes.BUNDLE, topo, cfg)

def numberGenerator():
    while True:
        time.sleep(1)
        randomNum = random.randint(1,10)
        print("Number: " + str(randomNum))
        yield randomNum

if __name__ == '__main__':
    main()
```

**Comment by ddebrunner** [comment]
Fixed.

**Comment by ddebrunner** [comment]
Not merged yet!
