### ISSUE TITLE
FileStreamTest fails frequently in distributed

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#197]
Expected tuple count: 60 != received: 20

junit.framework.AssertionFailedError: Expected tuple count: 60 != received: 20
at com.ibm.streamsx.topology.test.file.FileStreamsTest.runDirectoryWatcher(FileStreamsTest.java:82)
at com.ibm.streamsx.topology.test.file.FileStreamsTest.testDirectoryWatcherOrderWithDelete(FileStreamsTest.java:46)

**Comment by dlaboss** [comment]
the beacon/file-creator-sink operator (PE) is starting up before directory watcher operator (PE) and the first 2 batches of 40 files are gone after 800msec... before the watcher sees them.
