### ISSUE TITLE
IllegalArgumentException from verifySerializeable()

### ISSUE THREAD

**Issue by dlaboss** [IBMStreams/streamsx.topology#209]
Note, Non-generic variants of the predicate generator don't cause the problem.

I have a generic predicate generator for a test:
```
    private static <U> Predicate<Integer> predicateFn(final Supplier<U> someU, final U expected) {
        return new Predicate<Integer>() {
            public boolean test(Integer v) {
                if (someU.get() != expected)
                    throw new IllegalStateException("Didn't get expected SP value.  Expected " + expected + " got " + someU.get());
                return true;
            }};    }
```
When using it like:
```
        TStream<Integer> s1 = s.filter(predicateFn(strSp, "yo"));
        TStream<Integer> s2 = s.filter(predicateFn(byteSp, (byte)2));
```
An IllegalArgumentException is thrown building the op.  It's stating that "expected" field (the string "yo" in this case) isn't serializable.

```
    <error message="Functional logic argument com.ibm.streamsx.topology.test.api.FunctionalSubmissionParamsTest$3@326c70da contains a non-serializable field:val$expected ,ensure anonymous classes are declared in a static context." type="java.lang.IllegalArgumentException">java.lang.IllegalArgumentException: Functional logic argument com.ibm.streamsx.topology.test.api.FunctionalSubmissionParamsTest$3@326c70da contains a non-serializable field:val$expected ,ensure anonymous classes are declared in a static context.
	at com.ibm.streamsx.topology.internal.core.JavaFunctional.verifySerializable(JavaFunctional.java:197)
	at com.ibm.streamsx.topology.internal.core.JavaFunctional.addFunctionalOperator(JavaFunctional.java:65)
	at com.ibm.streamsx.topology.internal.core.JavaFunctional.addFunctionalOperator(JavaFunctional.java:57)
	at com.ibm.streamsx.topology.internal.core.StreamImpl.filter(StreamImpl.java:88)
	at com.ibm.streamsx.topology.test.api.FunctionalSubmissionParamsTest.AllTypesTest(FunctionalSubmissionParamsTest.java:243)
```

**Comment by ddebrunner** [comment]
`U extends Serializable` would be the way to fix this.

**Comment by dlaboss** [comment]
That did the trick. Thanks!
