### ISSUE TITLE
cryptic IAE with TWindow.aggregate() and sub-1msec time

### ISSUE THREAD

**Issue by dlaboss** [IBMStreams/streamsx.topology#211]
Running in EMBEDDED_TESTER...

```
        s.last(2).aggregate(functionListFn(someInt, 100), 100, TimeUnit.MICROSECONDS);
        // the following is OK
        // s.last(2).aggregate(functionListFn(someInt, 100), 1, TimeUnit.MILLISECONDS);
        ...
        complete(tester, expectedCount, 15, TimeUnit.SECONDS);
```

yields

```
    <error message="java.lang.IllegalArgumentException" type="java.util.concurrent.ExecutionException">java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException
    at java.util.concurrent.FutureTask.report(FutureTask.java:134)
    at java.util.concurrent.FutureTask.get(FutureTask.java:214)
    at com.ibm.streamsx.topology.internal.tester.TupleCollection.complete(TupleCollection.java:489)
    at com.ibm.streamsx.topology.test.TestTopology.complete(TestTopology.java:146)
    at com.ibm.streamsx.topology.test.api.FunctionalSubmissionParamsTest.MiscTest(FunctionalSubmissionParamsTest.java:226)
Caused by: java.lang.IllegalArgumentException
    at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(ScheduledThreadPoolExecutor.java:574)
    at com.ibm.streams.operator.internal.window.WindowHandler.scheduleRepeating(WindowHandler.java:264)
    at com.ibm.streams.operator.internal.window.WindowPartition$PeriodicTimerPolicy.activate(WindowPartition.java:263)
    at com.ibm.streams.operator.internal.window.sliding.SlidingCountEvictTimeTrigger.activate(SlidingCountEvictTimeTrigger.java:54)
    at com.ibm.streams.operator.internal.window.WindowHandler.activatePartitions(WindowHandler.java:392)
    at com.ibm.streams.operator.internal.window.WindowHandler$3.doWork(WindowHandler.java:385)
    at com.ibm.streams.operator.internal.window.WindowHandler$BackgroundWindowTask.run(WindowHandler.java:341)
    at com.ibm.streams.operator.internal.window.WindowHandler$2.handleNotification(WindowHandler.java:288)
    at javax.management.NotificationBroadcasterSupport.handleNotification(NotificationBroadcasterSupport.java:286)
    at javax.management.NotificationBroadcasterSupport$SendNotifJob.run(NotificationBroadcasterSupport.java:351)
    at javax.management.NotificationBroadcasterSupport$1.execute(NotificationBroadcasterSupport.java:336)
    at javax.management.NotificationBroadcasterSupport.sendNotification(NotificationBroadcasterSupport.java:259)
    at com.ibm.streams.operator.internal.management.NotifyInfo.notify(NotifyInfo.java:46)
    at com.ibm.streams.operator.internal.runtime.api.OperatorInfo.notify(OperatorInfo.java:178)
    at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.allPortsReady(OperatorAdapter.java:754)
    at com.ibm.streams.flow.internal.ExecutableGraphBase$2.call(ExecutableGraphBase.java:132)
    at com.ibm.streams.flow.internal.ExecutableGraphBase$2.call(ExecutableGraphBase.java:125)
    at java.util.concurrent.FutureTask.run(FutureTask.java:274)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1157)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:627)
    at java.lang.Thread.run(Thread.java:809)
</error>
```

**Comment by ddebrunner** [comment]
Part of this is that the embedded streams doesn't handle a window size of less than 1ms.

**Comment by ddebrunner** [comment]
Added issue against IBM Streams to fix the mock framework.

**Comment by dlaboss** [comment]
reminder to adjust WindowTest.testeriodicAggregateLastMicroseconds() to also run embedded once this is fixed.
