### ISSUE TITLE
CP4D_URL and other env vars required even when Instance provided

### ISSUE THREAD

**Issue by johnmac-ibm** [IBMStreams/streamsx.topology#2206]
The simple program below submits to a CP4D instance named someinstance at url for user someuser with mypassword when run as:

`java -cp .:$STREAMSX_TOPOLOGY_INSTALL/lib/com.ibm.streamsx.topology.jar:$STREAMS_INSTALL/lib/com.ibm.streams.operator.samples.jar Hello url someinstance someuser mypassword`

It creates the `Instance` to run on with `Instance.ofEndpoint()` from the cmdline args, and includes this in the config at submit.

This works if `STREAMS_INSTALL` is set and points to a version for the application can be built locally, but if it is empty or unset, an exception is thrown:

```
$ STREAMS_INSTALL= java -cp .:$STREAMSX_TOPOLOGY_INSTALL/lib/com.ibm.streamsx.topology.jar Hello url someinstance someuser mypassword
Jul 30, 2019 12:25:23 PM com.ibm.streamsx.rest.internal.RestUtils createHttpClient
WARNING: Insecure host connections enabled.
Jul 30, 2019 12:25:25 PM com.ibm.streamsx.rest.internal.RestUtils createHttpClient
WARNING: Insecure host connections enabled.
Exception in thread "main" java.lang.IllegalStateException: CDIST0329E: 'CP4D_URL' environment variable is not set.
	at com.ibm.streamsx.topology.internal.streams.Util.getenv(Util.java:83)
	at com.ibm.streamsx.rest.internal.ICP4DAuthenticator.of(ICP4DAuthenticator.java:31)
	at com.ibm.streamsx.topology.internal.context.streamsrest.DistributedStreamsRestContext.createSubmissionContext(DistributedStreamsRestContext.java:52)
	at com.ibm.streamsx.topology.internal.context.streamsrest.DistributedStreamsRestContext.createSubmissionContext(DistributedStreamsRestContext.java:34)
	at com.ibm.streamsx.topology.internal.context.remote.BuildRemoteContext._submit(BuildRemoteContext.java:40)
	at com.ibm.streamsx.topology.internal.context.remote.RemoteContextImpl.submit(RemoteContextImpl.java:30)
	at com.ibm.streamsx.topology.internal.context.RemoteContextForwarderStreamsContext.action(RemoteContextForwarderStreamsContext.java:34)
	at com.ibm.streamsx.topology.internal.context.JSONStreamsContext._submit(JSONStreamsContext.java:89)
	at com.ibm.streamsx.topology.internal.context.JSONStreamsContext.submit(JSONStreamsContext.java:77)
	at Hello.main(Hello.java:24)
```

I believe this is because `StreamsContextFactory.getStreamsContext()` creates a `RemoteDistributedStreamsContext` when `STREAMS_INSTALL` is unset or empty, but a `DistributedStreamsContext` if not:

https://github.com/IBMStreams/streamsx.topology/blob/c7551ffc75f8da2a1ec0d582323b092bcf4dfce7/java/src/com/ibm/streamsx/topology/context/StreamsContextFactory.java#L78-L84

The latter has code that will use the REST API if an instance is provided in the config, as checked in `preSubmit`:

https://github.com/IBMStreams/streamsx.topology/blob/c7551ffc75f8da2a1ec0d582323b092bcf4dfce7/java/src/com/ibm/streamsx/topology/internal/context/streams/DistributedStreamsContext.java#L92-L96

But the former does not appear to have similar logic, so it ends up calling `DistributedStreamsRestContext.createSubmissionContext()` as shown in the exception trace, which calls `ICP4DAuthenticator.of(null, null, null, null);` which wants the env vars set.

Simple Hello.java:
```
import java.util.HashMap;
import java.util.Map;

import com.ibm.streamsx.rest.Instance;
import com.ibm.streamsx.topology.TStream;
import com.ibm.streamsx.topology.Topology;
import com.ibm.streamsx.topology.context.ContextProperties;
import com.ibm.streamsx.topology.context.StreamsContext.Type;
import com.ibm.streamsx.topology.context.StreamsContextFactory;
import com.ibm.streamsx.topology.function.Supplier;


public class Hello {
    public static void main(String[] args) throws Exception {

        Topology topology = new Topology("Hello");
        topology.strings("Hello").print();

        Map<String, Object> config = new HashMap<>();
        config.put(ContextProperties.STREAMS_INSTANCE,
                Instance.ofEndpoint(args[0], args[1], args[2], args[3] , false));
        StreamsContextFactory
                .getStreamsContext(Type.DISTRIBUTED)
                .submit(topology, config);
    }
}
```

**Comment by ddebrunner** [comment]
Fixedin 1.13.1a
