### ISSUE TITLE
Pyspark not found on SAS even after including it with add_pip_package

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.topology#2301]
Using this notebook that uses PySpark library, the job fails with the error below.
What is the correct way to use/include the package?

Traceback (most recent call last):
  File "/home/streamsuser/.streams/var/Streams.sab_ALZ-production-lite-1-ebd8dfeb-579e-4019-9cc7-61238f623c87/b7aab3f2-fe36-425b-876d-415ca004c5ca/8f01a3324f3ba27e70269d69704439bf7cdcea91b962abbd923b06f4/output/toolkits/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/runtime.py", line 83, in __init__
    callable_ = _get_callable(callable_)
  File "/home/streamsuser/.streams/var/Streams.sab_ALZ-production-lite-1-ebd8dfeb-579e-4019-9cc7-61238f623c87/b7aab3f2-fe36-425b-876d-415ca004c5ca/8f01a3324f3ba27e70269d69704439bf7cdcea91b962abbd923b06f4/output/toolkits/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/runtime.py", line 71, in _get_callable
    ci = dill.loads(base64.b64decode(f))
  File "/usr/IBM/anaconda3/lib/python3.6/site-packages/dill/_dill.py", line 317, in loads
    return load(file, ignore)
  File "/usr/IBM/anaconda3/lib/python3.6/site-packages/dill/_dill.py", line 305, in load
    obj = pik.load()
  File "/home/streamsuser/.streams/var/..../com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/runtime.py", line 516, in __setstate__
    cm = importlib.import_module(mn[1])
  File "/usr/IBM/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pyspark'

**Comment by ddebrunner** [comment]
@natashadsilva Can you provide the code you are using.

**Comment by natashadsilva** [comment]
[Spark_Nov2019.ipynb.zip](https://github.com/IBMStreams/streamsx.topology/files/3821967/Spark_Nov2019.ipynb.zip)

Environment variables have to be set on the instance, so even after this problem is resolved it probably won't work.

**Comment by markheger** [comment]
no issue observed, tested with streamsx 1.14.11

```
Submitting to STREAMING_ANALYTICS_SERVICE context
JobId:  0 
Job name:  notebook::SparkScoring_0
```

```
python -m streamsx.scripts.info
streamsx==1.14.11 (package)
  location: /Users/xxx/anaconda36/lib/python3.6/site-packages
Python version:3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 15:01:53) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
PYTHONHOME=unset
PYTHONPATH=unset
PYTHONWARNINGS=unset
STREAMS_INSTALL=unset
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
```
