### ISSUE TITLE
test_st_rmtoolkit is failing.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#2304]
Running it against CPD instance I get failures, maybe some cases are intermittent.

```
======================================================================
ERROR: test_simple_1 (test_st_rmtoolkit.Testrmtoolkit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/streamsadmin/hostdir/topology/dev3/streamsx.topology/test/python/scripts/test_st_rmtoolkit.py", line 256, in test_simple_1
    random_tk_to_delete = random.choice(remote_test_tk_objects)
  File "/home/streamsadmin/miniconda3/envs/py36/lib/python3.6/random.py", line 260, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
```

```
======================================================================
ERROR: test_simple_2 (test_st_rmtoolkit.Testrmtoolkit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/streamsadmin/hostdir/topology/dev3/streamsx.topology/test/python/scripts/test_st_rmtoolkit.py", line 273, in test_simple_2
    random_tk_to_delete = random.choice(remote_test_tk_objects)
  File "/home/streamsadmin/miniconda3/envs/py36/lib/python3.6/random.py", line 260, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
```

**Comment by Karsten12** [comment]
Fixed in #2305
