### ISSUE TITLE
Error when calling streamsx-streamtool without sub command

### ISSUE THREAD

**Issue by markheger** [IBMStreams/streamsx.topology#2392]
```
streamsx-streamtool
Traceback (most recent call last):
  File "/home/streamsadmin/anaconda3/bin/streamsx-streamtool", line 8, in <module>
    sys.exit(main())
  File "/home/streamsadmin/anaconda3/lib/python3.6/site-packages/streamsx/scripts/streamtool.py", line 824, in main
    rc, extra_info = run_cmd(args)
  File "/home/streamsadmin/anaconda3/lib/python3.6/site-packages/streamsx/scripts/streamtool.py", line 792, in run_cmd
    username=cmd_args.User,
AttributeError: 'Namespace' object has no attribute 'User'
```

It should print the help text instead.

**Comment by markheger** [comment]
Expected result:

```
streamsx-streamtool
usage: streamsx-streamtool [-h] [--disable-ssl-verify]
                           {submitjob,canceljob,lsjobs,lsappconfig,rmappconfig,mkappconfig,chappconfig,getappconfig,rmtoolkit,lstoolkit,uploadtoolkit,updateoperators}
                           ...
streamsx-streamtool: error: argument subcmd: invalid choice: ' ' (choose from 'submitjob', 'canceljob', 'lsjobs', 'lsappconfig', 'rmappconfig', 'mkappconfig', 'chappconfig', 'getappconfig', 'rmtoolkit', 'lstoolkit', 'uploadtoolkit', 'updateoperators')
```
