### ISSUE TITLE
Out of memory error when using large python packages

### ISSUE THREAD

**Issue by RolefH** [IBMStreams/streamsx.topology#2429]
Python packages required by  a topology must now be included explicitly at build time, which means they are packaged into the sab file.
A simple topology that uses pyspark threw an OutofMemoryError at build time because the entire pyspark package was being included in the bundle.

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
at org.apache.http.util.ByteArrayBuffer.toByteArray(ByteArrayBuffer.java:179)
at org.apache.http.util.EntityUtils.toByteArray(EntityUtils.java:141)
at org.apache.http.client.fluent.Response.returnResponse(Response.java:105)
at com.ibm.streamsx.rest.build.StreamsRestUtils.rawStreamingGet(StreamsRestUtils.java:175)
at com.ibm.streamsx.rest.build.StreamsRestUtils.getFile(StreamsRestUtils.java:188)
at com.ibm.streamsx.rest.build.Artifact.download(Artifact.java:69)
```

**Comment by RolefH** [comment]
The download is implemented in the wrong way. The HTTP entity is buffered in memory. When the downloaded file is larger than `Inetger.MAX_VALUE` (~2G), a check in the HTTP client component throws an 
```
java.lang.IllegalArgumentException: HTTP entity too large to be buffered in memory
        at org.apache.http.util.Args.check(Args.java:36)
        at org.apache.http.util.EntityUtils.toByteArray(EntityUtils.java:129)
        at org.apache.http.client.fluent.Response.returnResponse(Response.java:105)
```
in
```
HttpResponse hResponse = response.returnResponse();
```
Instead of this, a _ResponseHandler_ implementation should be used to handle the response without the need of buffering.

See also https://hc.apache.org/httpcomponents-client-ga/tutorial/html/fluent.html, paragraph 5.1.1.
