### ISSUE TITLE
pip_add_package not installing all components. 

### ISSUE THREAD

**Issue by siegenth** [IBMStreams/streamsx.topology#2480]
I'm moving code from the cloud onto CP4D 3.0.1
- streamsx package version: 1.15.0
- I'm using this machine :  https://syss161.pok.stglabs.ibm.com:30562/

I'm adding the explict version of opencv.
```
topo.add_pip_package('opencv-contrib-python==4.2.0.32')
```
This is the import.....
```
import cv2
from cv2 import IMREAD_COLOR
from cv2 import COLOR_BGR2RGB
from cv2 import CascadeClassifier
from cv2 import imdecode
from cv2 import cvtColor
from PIL import Image
```

This is what I'm seeing in the log. 

```
Traceback (most recent call last):
  File "/home/streamsapp/ed08a6ebd65252b979e5a88b8a2ae6a05b246818bab810a6cb261079/output/toolkits/sampleEdgeVideo.VideoRcvKafka/opt/python/modules/cvsupport.py", line 8, in <module>
    import cv2
  File "/home/streamsapp/ed08a6ebd65252b979e5a88b8a2ae6a05b246818bab810a6cb261079/output/etc/streamsx.topology/python/lib/python3.6/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libSM.so.6: cannot open shared object file: No such file or directory
sh: /home/streamsapp/.streams/pes/72: Is a directory
Traceback (most recent call last):
  File "/home/streamsapp/ed08a6ebd65252b979e5a88b8a2ae6a05b246818bab810a6cb261079/output/toolkits/sampleEdgeVideo.VideoRcvKafka/opt/python/modules/cvsupport.py", line 8, in <module>
    import cv2
```

Regards

**Comment by markheger** [comment]
seems to be a common issue with opencv:
[see stackoverflow](https://stackoverflow.com/questions/47113029/importerror-libsm-so-6-cannot-open-shared-object-file-no-such-file-or-directo)

There are some packages to be installed in addition to python modules
`sudo yum install libXext libSM libXrender`

This is **not** under control of streamsx.
You need to customize the application image.

**Comment by siegenth** [comment]
Thanks for the pointer. Using the headless version resolves the problem:
```
topo.add_pip_package('opencv-contrib-python-headless')
```
