### ISSUE TITLE
Got a NullPointerException when executing examples

### ISSUE THREAD

**Issue by vesense** [IBMStreams/streamsx.topology#275]
I am a freshman of streamsx.topology. I got a NPE when I executed some examples in my eclipse.
Maybe the `ServiceLoader` cannot find the implemention of `abstract class FlowProvider`. I cannot find the jar.
```
Exception in thread "main" java.lang.NullPointerException
	at com.ibm.streams.flow.declare.OperatorGraphFactory.newGraph(OperatorGraphFactory.java:42)
	at com.ibm.streamsx.topology.builder.GraphBuilder.<init>(GraphBuilder.java:50)
	at com.ibm.streamsx.topology.Topology.<init>(Topology.java:102)
	at simple.FizzBuzz.main(FizzBuzz.java:23)
```
Could some people take a look? Thanks a lot.

**Comment by colindean** [comment]
What was the solution to the problem?

**Comment by williamClanton** [comment]
Is there a solution?
