### ISSUE TITLE
Exceptions in transform() are eaten and not reported

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.topology#277]
When running in EMBEDDED mode, if an exception is thrown from the code being executed as part of a transform(), the exception gets eaten and an "UnsupportedOperaionException" is reported instead. This makes pinpointing problems in the application very difficult and time consuming.

Here is a contrived sample application that demonstrates this behaviour: 

```
    Topology t = new Topology("Test");
    TStream<Number> src = t.numbers(1,2,3,4,5,6,7,8,9,10);
    src.transform(r -> {
        Double d = null;
        return r.doubleValue() * d;
    }).print();
    StreamsContextFactory.getEmbedded().submit(t).get();
```

I expected a NullPointerException to be thrown but instead I get the following:

```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.UnsupportedOperationException
    at java.util.concurrent.FutureTask.report(FutureTask.java:133)
    at java.util.concurrent.FutureTask.get(FutureTask.java:203)
    at test.Repro.main(Repro.java:19)
Caused by: java.lang.RuntimeException: java.lang.UnsupportedOperationException
    at com.ibm.streams.operator.samples.patterns.ProcessTupleProducer$1.run(ProcessTupleProducer.java:66)
    at java.lang.Thread.run(Thread.java:785)
    at com.ibm.streams.operator.internal.runtime.OperatorThreadFactory$2.run(OperatorThreadFactory.java:137)
Caused by: java.lang.UnsupportedOperationException
    at com.ibm.streams.flow.internal.OpExec.mustRethrowException(OpExec.java:359)
    at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.handleException(OperatorAdapter.java:1507)
    at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.processTuple(OperatorAdapter.java:1556)
    at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter$1.tuple(OperatorAdapter.java:829)
    at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter$1.tuple(OperatorAdapter.java:822)
    at com.ibm.streams.operator.internal.ports.SwitchingHandler$Alternate.tuple(SwitchingHandler.java:162)
    at com.ibm.streams.operator.internal.ports.DirectTuple.handleTuple(DirectTuple.java:108)
    at com.ibm.streams.operator.internal.ports.DirectTuple.tuple(DirectTuple.java:92)
    at com.ibm.streams.operator.internal.ports.DirectTuple.tuple(DirectTuple.java:36)
    at com.ibm.streams.flow.handlers.AbstractStreamForwarder.tuple(AbstractStreamForwarder.java:49)
    at com.ibm.streams.flow.handlers.AbstractStreamForwarder.tuple(AbstractStreamForwarder.java:49)
    at com.ibm.streams.flow.handlers.HandlerCollection.tuple(HandlerCollection.java:73)
    at com.ibm.streams.flow.handlers.AbstractStreamForwarder.tuple(AbstractStreamForwarder.java:49)
    at com.ibm.streams.operator.internal.ports.DirectTuple.handleTuple(DirectTuple.java:108)
    at com.ibm.streams.operator.internal.ports.DirectTuple.tuple(DirectTuple.java:92)
    at com.ibm.streams.operator.internal.ports.DirectTuple.tuple(DirectTuple.java:36)
    at com.ibm.streams.operator.internal.ports.OperatorOutputPort.submit(OperatorOutputPort.java:123)
    at com.ibm.streamsx.topology.internal.functional.ops.FunctionSource.process(FunctionSource.java:107)
    at com.ibm.streams.operator.samples.patterns.ProcessTupleProducer$1.run(ProcessTupleProducer.java:64)
    ... 2 more

```

**Comment by cancilla** [comment]
I don't agree that this is an enhancement, it should be marked as a bug. The topology framework is supposed to make development of streaming applications easier, however this issue is actually making it more difficult. By eating the underlying exception, developers will spend more time trying to determine what the problem actually rather than fixing the problem.
