### ISSUE TITLE
[Python] Passing non-callable to a function results in a TypeError

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#306]
To try and simplify the sample transform application i changed the source to:

`topo.source(["1", "2", "3"]);`

and received:

`TypeError: exceptions must derive from BaseException`

```
[streamsadmin@streamsqse modules]$ python3 myapp.py
Traceback (most recent call last):
  File "myapp.py", line 6, in <module>
    source = topo.source(["325", "457", "9325"])
  File "/home/streamsadmin/topology_pr/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/topology.py", line 28, in source
    op = self.graph.addOperator("com.ibm.streamsx.topology.functional.python::PyFunctionSource", func)
  File "/home/streamsadmin/topology_pr/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/graph.py", line 27, in addOperator
    op = SPLInvocation(len(self.operators), kind, function, name, {}, self)
  File "/home/streamsadmin/topology_pr/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/graph.py", line 85, in __init__
    self._addOperatorFunction(self.function)
  File "/home/streamsadmin/topology_pr/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/graph.py", line 157, in _addOperatorFunction
    raise "argument to _addOperatorFunction is not callable"
TypeError: exceptions must derive from BaseException
```

**Comment by markheger** [comment]
changed the samples/python/topology/simple/transform_sample.py

```

    # create the container for the topology that will hold the streams
    topo = Topology("transform_sample")
    
    # declare a source stream (`source`) that contains string tuples
    #source = topo.source(transform_sample_functions.int_strings_transform)
    source = topo.source(["1", "2", "3"]);
    
    # transform the stream of string tuples (`source`) to a stream of integer tuples (`i1`)
    i1 = source.map(transform_sample_functions.string_to_int)
    
    # adds 17 to each integer tuple 
    i2 = i1.map(transform_sample_functions.AddNum(17))
    
    # terminate the stream by printing each tuple to stdout
    i2.print()
    
    # execute the application in standalone mode
    streamsx.topology.context.submit("STANDALONE", topo)
```

no error observed anymore

```
python3 transform_sample.py 
18
19
20
```
