### ISSUE TITLE
Python: publish to jsonstring cannot serialize python sets

### ISSUE THREAD

**Issue by sdickes** [IBMStreams/streamsx.topology#412]
This is a known deficiency in json serialization in Python (since javascript does not have objects like Python sets) and a work around for a user would be to not use sets or to map set objects to list objects. 

@ddebrunner  The questions I have are 

-- should we support subscribe of an spl tuple containing a set but with doc to tell users that they need to map sets to lists?
-- or just document that an spl set is not supported within python subscription?

Here is the error I get during json serialization of a python set -- 

Traceback (most recent call last):
  File "/home/sdickes/.streams/var/Streams.sab_ALZ-smd3-inst1/7f3a62e3-4114-4c0e-890f-83dcb45b064d/4428f56bfc55dc3edec7b53b600d3b2bd0f81c332e9c04d3c3f53541/output/toolkits/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/runtime.py", line 170, in _wf
    jrv = json.dumps(rv, ensure_ascii=False)
  File "/usr/local/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.5/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.5/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.5/json/encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: {227201854, -1443668293, 1820446973, -1549346762, -766123506} is not JSON serializable
terminate called without an active exception
============================  SIGNAL SIGABRT     ============================

**Comment by ddebrunner** [comment]
Json serialization is independent of subscription.

So subscribe should be supported for SPL tuples containing SPL sets. 
Similarly complex32,64 as Python complex objects do not support serialization to JSON
