### ISSUE TITLE
KeyError "_pandasujson" when trying to use Pandas 

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.topology#431]
I am using the following code to read data from a file: 

**sources/TestSource.py:**

```
import pandas as pd

def data():
    data = pd.read_csv('/tmp/repo/DATA/rawData.csv', names=['d1', 'd2', 'd3'])
    tuples = [tuple(x) for x in data.values]
    for x in tuples:
        yield x
```

**test.py:**

```
from streamsx.topology.topology import Topology
import streamsx.topology.context
import sources.TestSource

def main():
    t = Topology("DataTester")
    srcStream = t.source(sources.TestSource.data)
    srcStream.sink(print)

    streamsx.topology.context.submit("STANDALONE", t.graph)

if __name__ == '__main__':
    main()
```

When I try to run the above application, I get the following error: 

```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    main()
  File "test.py", line 8, in main
    srcStream = t.source(sources.TestSource.data)
  File "/home/cancilla/git/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/topology.py", line 36, in source
    op = self.graph.addOperator("com.ibm.streamsx.topology.functional.python::PyFunctionSource", func)
  File "/home/cancilla/git/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/graph.py", line 42, in addOperator
    self.resolver.add_dependencies(inspect.getmodule(function))
  File "/home/cancilla/git/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 31, in add_dependencies
    self.add_dependencies(imported_module)
  File "/home/cancilla/git/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 31, in add_dependencies
    self.add_dependencies(imported_module)
  File "/home/cancilla/git/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 24, in add_dependencies
    self._add_dependency(module)
  File "/home/cancilla/git/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 56, in _add_dependency
    top_package = sys.modules[top_package_name]
KeyError: '_pandasujson'

```

I was able to work around this by adding the following code to lines 56 & 57 in **dependency.py**, although it's unclear why this package cannot be found or why it's being searched in the first place. 

```
 55             top_package_name = module.__name__.split('.')[0]
 56             if top_package_name not in sys.modules:
 57                 return
 58             top_package = sys.modules[top_package_name]

```

**Comment by ibmkendrick** [comment]
I tried the latest streamsx (0.6.1), and no longer can reproduce the problem. @cancilla , do you mind trying again?
