### ISSUE TITLE
cryptic failure if filter predicate (any "logic") isn't a static class

### ISSUE THREAD

**Issue by dlaboss** [IBMStreams/streamsx.topology#44]
Got to do something to improve this for users.  Took me a while to realize what the issue was.

I happened to define a Predicate instance in a non-static method.  
TStream.filter(nonStaticPredicate) threw:

Exception in thread "main" java.lang.RuntimeException: java.io.NotSerializableException: simple.CopyOfHelloWorld
	at com.ibm.streamsx.topology.internal.functional.ObjectUtils.serializeLogic(ObjectUtils.java:27)
	at com.ibm.streamsx.topology.internal.core.JavaFunctional.addFunctionalOperator(JavaFunctional.java:62)
	at com.ibm.streamsx.topology.internal.core.JavaFunctional.addFunctionalOperator(JavaFunctional.java:54)
	at com.ibm.streamsx.topology.internal.core.StreamImpl.filter(StreamImpl.java:60)
	at simple.CopyOfHelloWorld.nonStaticMethod(CopyOfHelloWorld.java:39)
	at simple.CopyOfHelloWorld.main(CopyOfHelloWorld.java:18)
Caused by: java.io.NotSerializableException: simple.CopyOfHelloWorld
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1212)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1586)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1547)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1470)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1206)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:368)
	at com.ibm.streamsx.topology.internal.functional.ObjectUtils.serializeLogic(ObjectUtils.java:23)
	... 5 more

can reproduce with:
private Topology nonStaticMethod() {
        Topology topology = new Topology("HelloWorld");
        Predicate<String> nilFilter = new Predicate<String>() {
			public boolean test(String tuple) { return true; }
    	};
        topology.strings("Hello", "World!").filter(nilFilter).print();
        return topology;
    }

**Comment by ddebrunner** [comment]
That should be already fixed

**Comment by ddebrunner** [comment]
There is the test testNonStaticContext() here:

https://github.com/IBMStreams/streamsx.topology/blob/master/test/java/src/com/ibm/streamsx/topology/test/api/TopologyTest.java

line 53

**Comment by dlaboss** [comment]
I see the newly generated IllegalArgumentException&msg now.
cancel/reject/close this issue
