### ISSUE TITLE
[Python Topology] Issue with importing pandas module

### ISSUE THREAD

**Issue by Tallwhitebro** [IBMStreams/streamsx.topology#440]
About a week ago I was having issues with importing the pandas module in a python topology app, this was resolved with the fix seen at the end of this issue: https://github.com/IBMStreams/streamsx.topology/issues/431

It was working fine until I setup jupyter notebook. Here is the error I now get:

```
Traceback (most recent call last):
  File "appAttempt1.py", line 14, in <module>
    main()
  File "appAttempt1.py", line 7, in main
    src = topo.source(appAttempt1_functions.readCsv)
  File "/home/jollers/toolkits/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/topology.py", line 36, in source
    op = self.graph.addOperator("com.ibm.streamsx.topology.functional.python::PyFunctionSource", func)
  File "/home/jollers/toolkits/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/graph.py", line 42, in addOperator
    self.resolver.add_dependencies(inspect.getmodule(function))
  File "/home/jollers/toolkits/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 31, in add_dependencies
    self.add_dependencies(imported_module)
  File "/home/jollers/toolkits/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 31, in add_dependencies
    self.add_dependencies(imported_module)
  File "/home/jollers/toolkits/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 31, in add_dependencies
    self.add_dependencies(imported_module)
  File "/home/jollers/toolkits/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 31, in add_dependencies
    self.add_dependencies(imported_module)
  File "/home/jollers/toolkits/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 31, in add_dependencies
    self.add_dependencies(imported_module)
  File "/home/jollers/toolkits/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 31, in add_dependencies
    self.add_dependencies(imported_module)
  File "/home/jollers/toolkits/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 31, in add_dependencies
    self.add_dependencies(imported_module)
  File "/home/jollers/toolkits/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 31, in add_dependencies
    self.add_dependencies(imported_module)
  File "/home/jollers/toolkits/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 31, in add_dependencies
    self.add_dependencies(imported_module)
  File "/home/jollers/toolkits/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 31, in add_dependencies
    self.add_dependencies(imported_module)
  File "/home/jollers/toolkits/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 31, in add_dependencies
    self.add_dependencies(imported_module)
  File "/home/jollers/toolkits/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 31, in add_dependencies
    self.add_dependencies(imported_module)
  File "/home/jollers/toolkits/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 26, in add_dependencies
    imported_modules = _get_imported_modules(module)
  File "/home/jollers/toolkits/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 144, in _get_imported_modules
    for alias, val in vars(module).items():
RuntimeError: dictionary changed size during iteration
```

Which refers to this function in the dependency.py file:

``` python
def _get_imported_modules(module):
    """
    Gets imported modules for a given module
    The following modules are excluded: 
    * built-in modules
    * modules that have "com.ibm.streamsx.topology" in the path
    * other system modules whose paths start with sys.prefix or sys.exec_prefix 
      that are not inside a site package
    Returns:
        a dictionary of module names => modules
    """
    imported_modules = {}
    #print ("vars({0}): {1}".format(module.__name__, vars(module)))
    for alias, val in vars(module).items():
        print(len(imported_modules))
        vars_module = None
        # module type
        if isinstance(val, types.ModuleType):
            vars_module = val
        # has __module__ attr, find module
        elif hasattr(val, '__module__') \
            and val.__module__ in sys.modules:
            vars_module = sys.modules[val.__module__]
        # if we found a module, determine if it should be included
        # in the list of dependencies
        if vars_module:    
            if not _is_builtin_module(vars_module) and \
               not _is_streamsx_module(vars_module) and \
               not _is_system_module(vars_module):
                print(vars_module.__name__, len(imported_modules))
                imported_modules[vars_module.__name__] = vars_module
    return imported_modules
```

The problem seems to stem from the line "imported_modules[vars_module.**name**] = vars_module". near the end of the _get_imported_modules function.

I have tried running simple test applications which don't import pandas and they run fine.

I appreciate any help or suggestions

**Comment by Tallwhitebro** [comment]
Here is a simple test which results in the same error:
### pandas.py
```python
from streamsx.topology.topology import Topology
import streamsx.topology.context
import testPandas

def main():
	topo = Topology("src")
	src = topo.source(testPandas.source)
	modify = src.transform(testPandas.pandafier)
	modify.print()
	streamsx.topology.context.submit("STANDALONE", topo.graph)


if __name__ == '__main__':
    main()
```
### testPandas.py
```python
import pandas as pd

def source():
	x = [1,2,3]
	return x

def pandafier(tuple):
	panda = pd.Series(tuple)
	return panda
```
### Output
```
[streamsadmin@streamsqse caloryApp]$ python pandasStreams.py 
Traceback (most recent call last):
  File "pandasStreams.py", line 14, in <module>
    main()
  File "pandasStreams.py", line 7, in main
    src = topo.source(testPandas.source)
  File "/home/streamsadmin/pythonTopology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/topology.py", line 36, in source
    op = self.graph.addOperator("com.ibm.streamsx.topology.functional.python::PyFunctionSource", func)
  File "/home/streamsadmin/pythonTopology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/graph.py", line 42, in addOperator
    self.resolver.add_dependencies(inspect.getmodule(function))
  File "/home/streamsadmin/pythonTopology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 31, in add_dependencies
    self.add_dependencies(imported_module)
  File "/home/streamsadmin/pythonTopology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 31, in add_dependencies
    self.add_dependencies(imported_module)
  File "/home/streamsadmin/pythonTopology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 31, in add_dependencies
    self.add_dependencies(imported_module)
  File "/home/streamsadmin/pythonTopology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 31, in add_dependencies
    self.add_dependencies(imported_module)
  File "/home/streamsadmin/pythonTopology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 31, in add_dependencies
    self.add_dependencies(imported_module)
  File "/home/streamsadmin/pythonTopology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 31, in add_dependencies
    self.add_dependencies(imported_module)
  File "/home/streamsadmin/pythonTopology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 31, in add_dependencies
    self.add_dependencies(imported_module)
  File "/home/streamsadmin/pythonTopology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 26, in add_dependencies
    imported_modules = _get_imported_modules(module)
  File "/home/streamsadmin/pythonTopology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/dependency.py", line 144, in _get_imported_modules
    for alias, val in vars(module).items():
RuntimeError: dictionary changed size during iteration
```

**Comment by ibmkendrick** [comment]
I tried the latest streamsx (0.6.1), and no longer can reproduce the problem.  @Tallwhitebro , do you mind trying again?
