### ISSUE TITLE
Topology build failure: AttributeError: module 'streamsx.spl.spl' has no attribute 'map'

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.topology#508]
I cloned the topology repository into my workspace and ran `ant`. I received the following error message:

```
test.toolkit:
     [exec] Traceback (most recent call last):Checking  /home/cancilla/git/streamsx.topology/test/python/spl/testtkpy/opt/python/streams/spl_samples.py for operators
     [exec] 
     [exec]   File "/home/cancilla/git/streamsx.topology/com.ibm.streamsx.topology/bin/spl-python-extract.py", line 255, in <module>
     [exec]     dynm = imp.load_source(name, mf)
     [exec]   File "/opt/anaconda3/lib/python3.5/imp.py", line 172, in load_source
     [exec]     module = _load(spec)
     [exec]   File "<frozen importlib._bootstrap>", line 693, in _load
     [exec]   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
     [exec]   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
     [exec]   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
     [exec]   File "/home/cancilla/git/streamsx.topology/test/python/spl/testtkpy/opt/python/streams/spl_samples.py", line 84, in <module>
     [exec]     @spl.map(attributes=spl.PassBy.position)
     [exec] AttributeError: module 'streamsx.spl.spl' has no attribute 'map'

```

**Comment by ddebrunner** [comment]
How does your spl.py in com.ibm.streamsx.topology/opt/python/packages/streamsx/spl compare to the one in the reop?

**Comment by ddebrunner** [comment]
I think your pythonpath must point to an older version of the toolkit.

**Comment by ddebrunner** [comment]
Can you try building with `PYTHONPATH` not set?

**Comment by cancilla** [comment]
You are correct, it's a `PYTHONPATH` issue. I changed the path to point to the version I am trying to build and it worked fine. The build also succeeds with PYTHONPATH not set. Thanks for the help!

**Comment by ddebrunner** [comment]
Thanks, leaving the issue open as the build should be independent of its environment.
