### ISSUE TITLE
test.application.api tests fails on Python 2.7.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#539]
```
 [exec] .
 [exec] ======================================================================
 [exec] ERROR: test_TopologyImportCommonNamespacePackage (__main__.TestTopologyMethods)
 [exec] ----------------------------------------------------------------------
 [exec] Traceback (most recent call last):
 [exec]   File "test1.py", line 201, in test_TopologyImportCommonNamespacePackage
 [exec]     import common_namespace.module1
 [exec] ImportError: No module named common_namespace.module1
 [exec]
 [exec] ----------------------------------------------------------------------
 [exec] Ran 23 tests in 311.311s
 [exec]
 [exec] FAILED (errors=1)
 [exec] Exception in thread Thread-39 (most likely raised during interpreter shutdown):
 [exec] Traceback (most recent call last):
 [exec]   File "/home/streamsadmin/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
 [exec]   File "/home/streamsadmin/anaconda2/lib/python2.7/threading.py", line 754, in run
 [exec]   File "/home/streamsadmin/topology/vanilla/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/context.py", line 145, in print_process_stderr
 [exec] <type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

BUILD FAILED

**Comment by sdickes** [comment]
Updating test setup based on this discussion -- 

http://stackoverflow.com/questions/1675734/how-do-i-create-a-namespace-package-in-python#comment1550515_1676069

tested a small change using anaconda2 and anaconda3 with good results. 

See pr #544

**Comment by ddebrunner** [comment]
Still seeing the second error:
```
     [exec] INFO: Standalone application completed: return code=134
     [exec] Exception in thread Thread-41 (most likely raised during interpreter shutdown):
     [exec] Traceback (most recent call last):
     [exec]   File "/home/streamsadmin/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
     [exec]   File "/home/streamsadmin/anaconda2/lib/python2.7/threading.py", line 754, in run
     [exec]   File "/home/streamsadmin/topology/bugfix/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/context.py", line 154, in _print_process_stderr
     [exec] <type 'exceptions.TypeError'>: 'NoneType' object is not callable

```

**Comment by sdickes** [comment]
I have not seen that error -- is there any other information about the setup or error?

**Comment by ddebrunner** [comment]
I just built as I normally do and then ran:

```
cd test/java
ant -Dtopology.test.python=$HOME/anaconda2/bin/python test.application.api > x2 2>&1
```

**Comment by ddebrunner** [comment]
This is now fixed, though there is a encoding issue in running the tests.

**Comment by ddebrunner** [comment]
Encoding issue entered as #610
