### ISSUE TITLE
Did java topology requirement change from json4j to gson in Streams 4.2?

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.topology#572]
I am running Streams 4.2 QSE.  I have an application that I have developed using the topology toolkit that from Github.  When I tried to run my application with topology toolkit in Streams v4.2, I get this error:
Exception in thread "main" java.lang.NoClassDefFoundError: com.google.gson.JsonElement
    at com.ibm.streamsx.topology.internal.streams.InvokeSubmit.fileJobConfig(InvokeSubmit.java:161)
    at com.ibm.streamsx.topology.internal.streams.InvokeSubmit.invoke(InvokeSubmit.java:69)
    at com.ibm.streamsx.topology.internal.context.DistributedStreamsContext.submitBundle(DistributedStreamsContext.java:44)
    at com.ibm.streamsx.topology.internal.context.DistributedStreamsContext.submit(DistributedStreamsContext.java:37)
    at com.ibm.streamsx.topology.internal.context.StreamsContextImpl.submit(StreamsContextImpl.java:19)
    at com.ibm.streamsx.health.hapi.services.OruR01Ingest.run(OruR01Ingest.java:74)
    at com.ibm.streamsx.health.hapi.services.OruR01Ingest.main(OruR01Ingest.java:39)
Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonElement
    at java.net.URLClassLoader.findClass(URLClassLoader.java:607)
    at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:846)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:825)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:325)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:805)
    ... 7 more

My project was set up with json4j before... and I am wondering if we now require gson instead?

**Comment by ddebrunner** [comment]
Both are used. The release of the toolkit includes gson 2.3.1 under `opt`.

**Comment by ddebrunner** [comment]
Gson is also referenced by the topology jar in its manifest class path.

**Comment by chanskw** [comment]
Interesting. My app worked in 4.1 without me having to add gson in the clasapath. But it does not work anymore on 4.2.

**Comment by ddebrunner** [comment]
Gson is used to generate the Json job submission config overlay, which is specific to 4.2.

**Comment by ddebrunner** [comment]
I just checked the 4.2 QSE and there should be no reason for you to manually include gson in any classpath. It should be brought in by the topology jar file.
