### ISSUE TITLE
Need to return details on why a build failed:

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#673]
A build failed (even with a correct SPL) and all I got back was this:

```
Jan 13, 2017 8:42:25 AM com.ibm.streamsx.topology.internal.context.remote.BuildServiceRemoteRESTWrapper remoteBuildAndSubmit
INFO: Submitting application to remote build.
Jan 13, 2017 8:42:57 AM com.ibm.streamsx.topology.internal.context.remote.BuildServiceRemoteRESTWrapper remoteBuildAndSubmit
SEVERE: The application failed to build.
https://streams-app-service.ng.bluemix.net/jax-rs/builds/service_instances/3a4b0956-ec2c-4cd0-98e7-9da7c70c0fa3/service_bindings/3ed52a77-355f-4b87-93c0-8dabf05d6adf?build_id=48&output_id=ff3454fa-fcb5-43ca-93e4-d54d8984a702
Exception in thread "main" java.lang.IllegalStateException: Error submitting archive for compilation:
"CDISA5488E The 48 build failed for the following domain: standard1."

at com.ibm.streamsx.topology.internal.context.remote.BuildServiceRemoteRESTWrapper.remoteBuildAndSubmit(BuildServiceRemoteRESTWrapper.java:67)
at com.ibm.streamsx.topology.internal.context.remote.RemoteBuildAndSubmitRemoteContext.doSubmit(RemoteBuildAndSubmitRemoteContext.java:32)
at com.ibm.streamsx.topology.internal.context.remote.RemoteBuildAndSubmitRemoteContext.submit(RemoteBuildAndSubmitRemoteContext.java:23)
at com.ibm.streamsx.topology.context.remote.RemoteContextSubmit.main(RemoteContextSubmit.java:33)
```

**Comment by ddebrunner** [comment]
There is a IBM Streams bug that needs to be fixed first.
