### ISSUE TITLE
Java streams jobs never unhealthy

### ISSUE THREAD

**Issue by afilichkin** [IBMStreams/streamsx.topology#751]
Hi,
I'm using Streams 4.1.1.0.
When in process(StreamingInput<Tuple> inputStream, Tuple tuple) method I throw some exception it goes to shutdown and then again run initialize,allPortsReady,process methods.

Job is unhealthy only for some short period than it becomes healthy. For old Streams 3 if we in shutdown method than we  unhealthy forever.

`public class Operator extends com.ibm.streams.operator.AbstractOperator {
    @Override
    public synchronized void initialize(OperatorContext context) throws Exception {
        // Must call super.initialize(context) to correctly setup an operator.
        super.initialize(context);
        System.out.println("initialize ");     
    }

    @Override
    public synchronized void allPortsReady() throws Exception {
        super.allPortsReady();
        System.out.println("allPortsReady ");      
    }

    @Override
    public final void process(StreamingInput<Tuple> inputStream, Tuple tuple) throws Exception {
        //it handles HEARTBEAT from DPRouter
        super.process(inputStream, tuple);
        throw new RuntimeException("My error");
    }

    @Override
    public void processPunctuation(StreamingInput<Tuple> stream, Punctuation mark) throws Exception {
        // For window markers, punctuate all output ports
        super.processPunctuation(stream, mark);
    }

    @Override
    public synchronized void shutdown() throws Exception {
        System.out.println("shutdown ");
        super.shutdown();
    }

}`

log:
**initialize 
allPortsReady**
Exception in thread "Thread-16" java.lang.RuntimeException: My error
	at com.Operator.process(SamOperator.java:45)
	at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.processTuple(OperatorAdapter.java:1554)
	at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter$1.tuple(OperatorAdapter.java:829)
	at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter$1.tuple(OperatorAdapter.java:822)
	at com.ibm.streams.operator.internal.ports.SwitchingHandler$Alternate.tuple(SwitchingHandler.java:162)
	at com.ibm.streams.operator.internal.network.DeserializingStream.tuple(DeserializingStream.java:76)
	at com.ibm.streams.operator.internal.network.DeserializingStream.processRawTuple(DeserializingStream.java:65)
	at com.ibm.streams.operator.internal.runtime.api.InputPortsConduit.processRawTuple(InputPortsConduit.java:100)
	at com.ibm.streams.operator.internal.jni.JNIBridge.process(JNIBridge.java:310)
**shutdown 
initialize 
allPortsReady**

**Comment by ddebrunner** [comment]
Streams 4.0 changed the behaviour so that operators are restartable and relocatable by default.
In Streams 3.0 operators were not restartable and not relocatable by default.

You can change this by setting the restartable/relocatable config elements on the operator invocation.

When an operator fails its PE is restarted, if an operator/PE cannot be restarted successfully after a number of attempts (10 I think), it will just stop and have to be manually restarted.

**Comment by afilichkin** [comment]
Thank you for the explanation
