### ISSUE TITLE
Remote build submission from Python does not handle errors gracefully.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#782]
Trying to submit with the service down does not return a valid error code from submit (it returns `None`) .
Multiple stack traces appear, trying to process the results file.

```
2017-02-28 00:28:19,373 - streamsx.topology.py_submit - INFO - Generating SPL and submitting application.
Feb 28, 2017 12:28:21 AM com.ibm.streamsx.topology.internal.context.remote.BuildServiceRemoteRESTWrapper remoteBuildAndSubmit
INFO: Streaming Analytics Service (debrunne-streams2): Checking status
Feb 28, 2017 12:28:23 AM com.ibm.streamsx.topology.internal.streaminganalytics.RestUtils checkInstanceStatus
INFO: Streaming Analytics Service (debrunne-streams2): instance status response:{"state":"STARTED","plan":"Standard","enabled":true,"status":"partiallyFailed"}
Exception in thread "main" java.lang.IllegalStateException: Service is not running!
at com.ibm.streamsx.topology.internal.streaminganalytics.RestUtils.checkInstanceStatus(RestUtils.java:80)
at com.ibm.streamsx.topology.internal.context.remote.BuildServiceRemoteRESTWrapper.remoteBuildAndSubmit(BuildServiceRemoteRESTWrapper.java:57)
at com.ibm.streamsx.topology.internal.context.remote.RemoteBuildAndSubmitRemoteContext.doSubmit(RemoteBuildAndSubmitRemoteContext.java:46)
at com.ibm.streamsx.topology.internal.context.remote.RemoteBuildAndSubmitRemoteContext._submit(RemoteBuildAndSubmitRemoteContext.java:35)
at com.ibm.streamsx.topology.internal.context.remote.RemoteContextImpl.submit(RemoteContextImpl.java:12)
at com.ibm.streamsx.topology.context.remote.RemoteContextSubmit.main(RemoteContextSubmit.java:33)
2017-02-28 00:28:23,978 - streamsx.topology.py_submit - ERROR - Results file doesn't contain valid JSON
Traceback (most recent call last):
  File "/home/streamsadmin/topology/42test/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/context.py", line 157, in submit
    results_json = json.loads(_file.read())
  File "/home/streamsadmin/anaconda3/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/home/streamsadmin/anaconda3/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/streamsadmin/anaconda3/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2017-02-28 00:28:23,980 - streamsx.topology.py_submit - ERROR - Error starting java subprocess for submission
Traceback (most recent call last):
  File "/home/streamsadmin/topology/42test/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/context.py", line 157, in submit
    results_json = json.loads(_file.read())
  File "/home/streamsadmin/anaconda3/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/home/streamsadmin/anaconda3/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/streamsadmin/anaconda3/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2017-02-28 00:28:23,980 - streamsx.topology.py_submit - ERROR - Error while submitting application.
Traceback (most recent call last):
  File "/home/streamsadmin/topology/42test/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/context.py", line 81, in submit
    return context_submitter.submit()
  File "/home/streamsadmin/topology/42test/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/context.py", line 157, in submit
    results_json = json.loads(_file.read())
  File "/home/streamsadmin/anaconda3/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/home/streamsadmin/anaconda3/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/streamsadmin/anaconda3/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
None

```

**Comment by ddebrunner** [comment]
It would be good to have the return from submit include information from the status check, maybe even the build check. Then a test could be skipped if the service was not started.

**Comment by ibmkendrick** [comment]
I'm observing the same error when submitting with a STANDALONE context as well.

**Comment by ibmkendrick** [comment]
What is the expected behavior for submit() when an exception occurs? Should it:
* propagate the exception to the caller? or
* store the exception (i.e. sys.exc_info()), into the returned dict?

**Comment by locke105** [comment]
I would expect an Exception to be raised if the submit task fails. Python is generally an 'Easier to Ask For Forgiveness' language.

**Comment by wmarshall484** [comment]
I believe this is resolved. Will close unless there are additional comments.
