### ISSUE TITLE
ERROR: test_BundlePath (test2.TestBundleMethodsNew)

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#836]
This fails when STREAMS_INSTALL is not set, which is a valid mode for running all the tests.

Test should be skipped when it cannot be run due to environment.

ERROR: test_BundlePath (test2.TestBundleMethodsNew)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/streamsadmin/topology/42test/streamsx.topology/test/python/topology/test2.py", line 23, in test_BundlePath
    result = streamsx.topology.context.submit("BUNDLE", topo)
  File "/home/streamsadmin/topology/42test/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/context.py", line 80, in submit
    context_submitter = _SubmitContextFactory(graph, config, username, password).get_submit_context(ctxtype)
  File "/home/streamsadmin/topology/42test/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/context.py", line 402, in get_submit_context
    raise UnsupportedContextException(ctxtype + " must be submitted when a streams install is present.")
streamsx.topology.context.UnsupportedContextException: BUNDLE must be submitted when a streams install is present.

**Comment by ibmkendrick** [comment]
Added condition to skip `TestBundleMethodsNew` when Streams install is not available.
