### ISSUE TITLE
FAIL: test_TopologySourceList (test2.TestBluemixTopologyMethodsNew)

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#853]
FAIL: test_TopologySourceList (test2.TestBluemixTopologyMethodsNew)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/streamsadmin/topology/dev/streamsx.topology/test/python/topology/test2.py", line 98, in test_TopologySourceList
    verifyNoKeepArtifacts(self, result)
  File "/home/streamsadmin/topology/dev/streamsx.topology/test/python/topology/test2.py", line 42, in verifyNoKeepArtifacts
    test.assertNotIn('archivePath', submissionResult)
AssertionError: 'archivePath' unexpectedly found in {'enabled': True, 'jobId': '64', 'archivePath': '/home/streamsadmin/topology/dev/streamsx.topology/test/python/topology/tk7924466065939052888.zip', 'artifact': '1296', 'name': 'test2::test_TopologySourceList_64', 'state': 'STARTED', 'status': 'running', 'application': 'test2::test_TopologySourceList', 'return_code': 0, 'plan': 'Standard'}

**Comment by ddebrunner** [comment]
I assume this is related.

FAIL: test_TopologySourceFn (test2.TestBluemixTopologyMethodsNew)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/streamsadmin/topology/dev/streamsx.topology/test/python/topology/test2.py", line 108, in test_TopologySourceFn
    verifyKeepArtifacts(self, tester.result['submission_result'])
  File "/home/streamsadmin/topology/dev/streamsx.topology/test/python/topology/test2.py", line 32, in verifyKeepArtifacts
    assertBundlePath(test, submissionResult)
  File "/home/streamsadmin/topology/dev/streamsx.topology/test/python/topology/test2.py", line 17, in assertBundlePath
    test.assertIn('bundlePath', submissionResult)
AssertionError: 'bundlePath' not found in {'enabled': True, 'jobId': '62', 'archivePath': '/home/streamsadmin/topology/dev/streamsx.topology/test/python/topology/tk5852025518565248015.zip', 'artifact': '1294', 'name': 'test2::test_TopologySourceFn_62', 'state': 'STARTED', 'status': 'running', 'toolkitRoot': '/home/streamsadmin/topology/dev/streamsx.topology/test/python/topology/tk5852025518565248015', 'application': 'test2::test_TopologySourceFn', 'return_code': 0, 'plan': 'Standard'}

**Comment by ibmkendrick** [comment]
I didn't handle `forceRemoteBuild` correctly.  I'll fix this.
