### ISSUE TITLE
FAIL: test_KeepArtifacts (test2.TestToolkitMethodsNew)

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#906]
See this sometimes.
```
FAIL: test_KeepArtifacts (test2.TestToolkitMethodsNew)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/streamsadmin/topology/dev/streamsx.topology/test/python/topology/test2.py", line 91, in test_KeepArtifacts
    verifyArtifacts(self)
  File "/home/streamsadmin/topology/dev/streamsx.topology/test/python/topology/test2.py", line 47, in verifyArtifacts
    assertArchivePath(test, test.result)
  File "/home/streamsadmin/topology/dev/streamsx.topology/test/python/topology/test2.py", line 37, in assertArchivePath
    test.assertIn('archivePath', submissionResult)
AssertionError: 'archivePath' not found in <streamsx.topology.context.SubmissionResult object at 0x7fd2c682dcc0>
```

**Comment by ibmkendrick** [comment]
Can reproduce if STREAMS_INSTALL is unset.

**Comment by ddebrunner** [comment]
reopening - still seeing this when running with STREAMS_INSTALL not set.
@ibmkendrick 
```
https://github.com/IBMStreams/streamsx.topology/commit/d6d2b2bd6cb7c4bc629ea27fe2cd5690342ec1a9
```

**Comment by ibmkendrick** [comment]
@ddebrunner , can you check if the unit test is running with the latest code?  The traceback above has a reference to line 47 (which seems to be old code)

**Comment by ddebrunner** [comment]
@ibmkendrick You are most likely correct, I did everything except the pull - will rerun - Thanks!

**Comment by ddebrunner** [comment]
Confirmed working with latest code.
