### ISSUE TITLE
get_resource_allocations() fails against Streaming Analytics service.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#952]
The response always gets a 403, with text like:

```
{
id: "CDISA5263E",
message: "CDISA5263E The  XXXX-name=removed-XXXX user is not authorized to list resources for the XXXinstance-id-removedXXXX instance in the following domain: XXdomain-idXXX."
}
```

Seems like this should be handled better than:

```
ERROR: test_basic_calls (test_rest_bluemix.TestRestFeaturesBluemix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/streamsadmin/topology/42test/streamsx.topology/test/python/rest/common_tests.py", line 122, in test_basic_calls
    self.tester.test(self.test_ctxtype, self.test_config)
  File "/home/streamsadmin/topology/42test/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/tester.py", line 249, in test
    passed = self._streaming_analytics_test(ctxtype, config)
  File "/home/streamsadmin/topology/42test/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/tester.py", line 296, in _streaming_analytics_test
    return self._distributed_wait_for_result()
  File "/home/streamsadmin/topology/42test/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/tester.py", line 307, in _distributed_wait_for_result
    raise self.local_check_exception
  File "/home/streamsadmin/topology/42test/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/tester.py", line 319, in _call_local_check
    self.local_check_value = self.local_check()
  File "/home/streamsadmin/topology/42test/streamsx.topology/test/python/rest/common_tests.py", line 107, in _call_rest_apis
    primitives_caller.check_domain(self, domain)
  File "/home/streamsadmin/topology/42test/streamsx.topology/test/python/rest/primitives_caller.py", line 48, in check_domain
    _fetch_from_domain(tc, domain)
  File "/home/streamsadmin/topology/42test/streamsx.topology/test/python/rest/primitives_caller.py", line 56, in _fetch_from_domain
    _check_non_empty_list(tc, domain.get_resource_allocations(), ResourceAllocation)
  File "/home/streamsadmin/topology/42test/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/rest_primitives.py", line 583, in get_resource_allocations
    return self._get_elements(self.resourceAllocations, 'resourceAllocations', ResourceAllocation)
  File "/home/streamsadmin/topology/42test/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/rest_primitives.py", line 85, in _get_elements
    json_elements = self.rest_client.make_request(url)[key]
KeyError: 'resourceAllocations'

```

**Comment by markheger** [comment]
close because tests passed
```
python3 -u -m unittest test_rest.TestSasRestFeatures
----------------------------------------------------------------------
Ran 5 tests in 309.447s

OK
```
